/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminAbout: typeof import('./components/admin/AdminAbout.vue')['default']
    AdminDashboard: typeof import('./components/admin/AdminDashboard.vue')['default']
    AdminLibSort: typeof import('./components/admin/AdminLibSort.vue')['default']
    AdminLogs: typeof import('./components/admin/AdminLogs.vue')['default']
    AdminMetadata: typeof import('./components/admin/AdminMetadata.vue')['default']
    AdminMetadataMgr: typeof import('./components/admin/AdminMetadataMgr.vue')['default']
    AdminPhotos: typeof import('./components/admin/AdminPhotos.vue')['default']
    AdminPlugins: typeof import('./components/admin/AdminPlugins.vue')['default']
    AdminProfile: typeof import('./components/admin/AdminProfile.vue')['default']
    AdminScheduledTasks: typeof import('./components/admin/AdminScheduledTasks.vue')['default']
    AdminTranscode: typeof import('./components/admin/AdminTranscode.vue')['default']
    AdminUserEdit: typeof import('./components/admin/AdminUserEdit.vue')['default']
    AdminUsers: typeof import('./components/admin/AdminUsers.vue')['default']
    AppDrawer: typeof import('./components/layout/AppDrawer.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    BaseAvatar: typeof import('./components/BaseAvatar.vue')['default']
    BaseEmptyState: typeof import('./components/BaseEmptyState.vue')['default']
    BaseScroller: typeof import('./components/BaseScroller.vue')['default']
    BaseSelect: typeof import('./components/BaseSelect.vue')['default']
    CastRow: typeof import('./components/detail/CastRow.vue')['default']
    ContextMenu: typeof import('./components/ContextMenu.vue')['default']
    DetailHero: typeof import('./components/detail/DetailHero.vue')['default']
    FilePickerModal: typeof import('./components/FilePickerModal.vue')['default']
    FullscreenPlayer: typeof import('./components/playback/FullscreenPlayer.vue')['default']
    GlobalToast: typeof import('./components/GlobalToast.vue')['default']
    GlobalUiContainer: typeof import('./components/GlobalUiContainer.vue')['default']
    HomeHero: typeof import('./components/home/HomeHero.vue')['default']
    LibraryContextMenu: typeof import('./components/LibraryContextMenu.vue')['default']
    LibrarySettingsModal: typeof import('./components/LibrarySettingsModal.vue')['default']
    MediaCard: typeof import('./components/media/MediaCard.vue')['default']
    MediaPoster: typeof import('./components/media/MediaPoster.vue')['default']
    MediaRow: typeof import('./components/media/MediaRow.vue')['default']
    MetadataManagerModal: typeof import('./components/MetadataManagerModal.vue')['default']
    MusicPlayerBar: typeof import('./components/playback/MusicPlayerBar.vue')['default']
    PageHeader: typeof import('./components/detail/PageHeader.vue')['default']
    PlaybackOverlay: typeof import('./components/playback/PlaybackOverlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeasonEpisodes: typeof import('./components/detail/SeasonEpisodes.vue')['default']
    SetupWizardModal: typeof import('./components/SetupWizardModal.vue')['default']
    SimilarRow: typeof import('./components/detail/SimilarRow.vue')['default']
  }
}

// For TSX support
declare global {
  const AdminAbout: typeof import('./components/admin/AdminAbout.vue')['default']
  const AdminDashboard: typeof import('./components/admin/AdminDashboard.vue')['default']
  const AdminLibSort: typeof import('./components/admin/AdminLibSort.vue')['default']
  const AdminLogs: typeof import('./components/admin/AdminLogs.vue')['default']
  const AdminMetadata: typeof import('./components/admin/AdminMetadata.vue')['default']
  const AdminMetadataMgr: typeof import('./components/admin/AdminMetadataMgr.vue')['default']
  const AdminPhotos: typeof import('./components/admin/AdminPhotos.vue')['default']
  const AdminPlugins: typeof import('./components/admin/AdminPlugins.vue')['default']
  const AdminProfile: typeof import('./components/admin/AdminProfile.vue')['default']
  const AdminScheduledTasks: typeof import('./components/admin/AdminScheduledTasks.vue')['default']
  const AdminTranscode: typeof import('./components/admin/AdminTranscode.vue')['default']
  const AdminUserEdit: typeof import('./components/admin/AdminUserEdit.vue')['default']
  const AdminUsers: typeof import('./components/admin/AdminUsers.vue')['default']
  const AppDrawer: typeof import('./components/layout/AppDrawer.vue')['default']
  const AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
  const BaseAvatar: typeof import('./components/BaseAvatar.vue')['default']
  const BaseEmptyState: typeof import('./components/BaseEmptyState.vue')['default']
  const BaseScroller: typeof import('./components/BaseScroller.vue')['default']
  const BaseSelect: typeof import('./components/BaseSelect.vue')['default']
  const CastRow: typeof import('./components/detail/CastRow.vue')['default']
  const ContextMenu: typeof import('./components/ContextMenu.vue')['default']
  const DetailHero: typeof import('./components/detail/DetailHero.vue')['default']
  const FilePickerModal: typeof import('./components/FilePickerModal.vue')['default']
  const FullscreenPlayer: typeof import('./components/playback/FullscreenPlayer.vue')['default']
  const GlobalToast: typeof import('./components/GlobalToast.vue')['default']
  const GlobalUiContainer: typeof import('./components/GlobalUiContainer.vue')['default']
  const HomeHero: typeof import('./components/home/HomeHero.vue')['default']
  const LibraryContextMenu: typeof import('./components/LibraryContextMenu.vue')['default']
  const LibrarySettingsModal: typeof import('./components/LibrarySettingsModal.vue')['default']
  const MediaCard: typeof import('./components/media/MediaCard.vue')['default']
  const MediaPoster: typeof import('./components/media/MediaPoster.vue')['default']
  const MediaRow: typeof import('./components/media/MediaRow.vue')['default']
  const MetadataManagerModal: typeof import('./components/MetadataManagerModal.vue')['default']
  const MusicPlayerBar: typeof import('./components/playback/MusicPlayerBar.vue')['default']
  const PageHeader: typeof import('./components/detail/PageHeader.vue')['default']
  const PlaybackOverlay: typeof import('./components/playback/PlaybackOverlay.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SeasonEpisodes: typeof import('./components/detail/SeasonEpisodes.vue')['default']
  const SetupWizardModal: typeof import('./components/SetupWizardModal.vue')['default']
  const SimilarRow: typeof import('./components/detail/SimilarRow.vue')['default']
}