/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDrawer: typeof import('./components/layout/AppDrawer.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    BaseScroller: typeof import('./components/BaseScroller.vue')['default']
    BaseSelect: typeof import('./components/BaseSelect.vue')['default']
    CastRow: typeof import('./components/detail/CastRow.vue')['default']
    ContextMenu: typeof import('./components/ContextMenu.vue')['default']
    DetailHero: typeof import('./components/detail/DetailHero.vue')['default']
    FilePickerModal: typeof import('./components/FilePickerModal.vue')['default']
    FullscreenPlayer: typeof import('./components/playback/FullscreenPlayer.vue')['default']
    GlobalUiContainer: typeof import('./components/GlobalUiContainer.vue')['default']
    GuidedTourOverlay: typeof import('./components/GuidedTourOverlay.vue')['default']
    HomeHero: typeof import('./components/home/HomeHero.vue')['default']
    MediaCard: typeof import('./components/media/MediaCard.vue')['default']
    MediaPoster: typeof import('./components/media/MediaPoster.vue')['default']
    MediaRow: typeof import('./components/media/MediaRow.vue')['default']
    MetadataManagerModal: typeof import('./components/MetadataManagerModal.vue')['default']
    PageHeader: typeof import('./components/detail/PageHeader.vue')['default']
    PlaybackOverlay: typeof import('./components/playback/PlaybackOverlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeasonEpisodes: typeof import('./components/detail/SeasonEpisodes.vue')['default']
    SetupWizardModal: typeof import('./components/SetupWizardModal.vue')['default']
    SimilarRow: typeof import('./components/detail/SimilarRow.vue')['default']
  }
}

// For TSX support
declare global {
  const AppDrawer: typeof import('./components/layout/AppDrawer.vue')['default']
  const AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
  const BaseScroller: typeof import('./components/BaseScroller.vue')['default']
  const BaseSelect: typeof import('./components/BaseSelect.vue')['default']
  const CastRow: typeof import('./components/detail/CastRow.vue')['default']
  const ContextMenu: typeof import('./components/ContextMenu.vue')['default']
  const DetailHero: typeof import('./components/detail/DetailHero.vue')['default']
  const FilePickerModal: typeof import('./components/FilePickerModal.vue')['default']
  const FullscreenPlayer: typeof import('./components/playback/FullscreenPlayer.vue')['default']
  const GlobalUiContainer: typeof import('./components/GlobalUiContainer.vue')['default']
  const GuidedTourOverlay: typeof import('./components/GuidedTourOverlay.vue')['default']
  const HomeHero: typeof import('./components/home/HomeHero.vue')['default']
  const MediaCard: typeof import('./components/media/MediaCard.vue')['default']
  const MediaPoster: typeof import('./components/media/MediaPoster.vue')['default']
  const MediaRow: typeof import('./components/media/MediaRow.vue')['default']
  const MetadataManagerModal: typeof import('./components/MetadataManagerModal.vue')['default']
  const PageHeader: typeof import('./components/detail/PageHeader.vue')['default']
  const PlaybackOverlay: typeof import('./components/playback/PlaybackOverlay.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SeasonEpisodes: typeof import('./components/detail/SeasonEpisodes.vue')['default']
  const SetupWizardModal: typeof import('./components/SetupWizardModal.vue')['default']
  const SimilarRow: typeof import('./components/detail/SimilarRow.vue')['default']
}