create table if not exists jobs (
    id bigserial primary key,
    public_id uuid not null default gen_random_uuid(),
    job_type text not null,
    status text not null default 'queued',
    queue_name text not null default 'default',
    priority integer not null default 0,
    payload jsonb not null default '{}'::jsonb,
    dedupe_key text,
    run_at timestamptz not null default now(),
    locked_by text,
    locked_until timestamptz,
    attempts integer not null default 0,
    max_attempts integer not null default 3,
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    finished_at timestamptz,
    unique (public_id),
    unique (dedupe_key),
    check (length(trim(job_type)) > 0),
    check (length(trim(queue_name)) > 0),
    check (status in ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
    check (attempts >= 0),
    check (max_attempts > 0),
    check (locked_until is null or locked_by is not null)
);

create table if not exists job_runs (
    id bigserial primary key,
    job_id bigint not null references jobs(id) on delete cascade,
    worker_id text not null,
    status text not null default 'running',
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    error_message text,
    metrics jsonb not null default '{}'::jsonb,
    check (length(trim(worker_id)) > 0),
    check (status in ('running', 'succeeded', 'failed', 'cancelled')),
    check (finished_at is null or finished_at >= started_at)
);

create table if not exists job_events (
    id bigserial primary key,
    job_id bigint references jobs(id) on delete cascade,
    job_run_id bigint references job_runs(id) on delete set null,
    event_type text not null,
    event_level text not null default 'info',
    message text,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    check (length(trim(event_type)) > 0),
    check (event_level in ('debug', 'info', 'warn', 'error'))
);

create table if not exists event_outbox (
    id bigserial primary key,
    public_id uuid not null default gen_random_uuid(),
    event_type text not null,
    aggregate_type text not null,
    aggregate_id text not null,
    payload jsonb not null default '{}'::jsonb,
    status text not null default 'pending',
    available_at timestamptz not null default now(),
    attempts integer not null default 0,
    max_attempts integer not null default 10,
    locked_by text,
    locked_until timestamptz,
    last_error text,
    created_at timestamptz not null default now(),
    delivered_at timestamptz,
    unique (public_id),
    check (length(trim(event_type)) > 0),
    check (length(trim(aggregate_type)) > 0),
    check (length(trim(aggregate_id)) > 0),
    check (status in ('pending', 'delivering', 'delivered', 'failed', 'discarded')),
    check (attempts >= 0),
    check (max_attempts > 0)
);

create table if not exists scheduled_tasks (
    id bigserial primary key,
    public_id uuid not null default gen_random_uuid(),
    task_key text not null,
    task_type text not null,
    owner_type text not null default 'core',
    owner_id text,
    enabled boolean not null default false,
    schedule_kind text not null,
    schedule_value text not null,
    next_run_at timestamptz,
    last_run_at timestamptz,
    timeout_seconds integer not null default 300,
    max_concurrency integer not null default 1,
    failure_count integer not null default 0,
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (task_key),
    unique (public_id),
    check (length(trim(task_key)) > 0),
    check (length(trim(task_type)) > 0),
    check (owner_type in ('core', 'plugin')),
    check (schedule_kind in ('cron', 'interval')),
    check (length(trim(schedule_value)) > 0),
    check (timeout_seconds > 0),
    check (max_concurrency > 0),
    check (failure_count >= 0)
);

create table if not exists webhook_subscriptions (
    id bigserial primary key,
    public_id uuid not null default gen_random_uuid(),
    name text not null,
    target_url text not null,
    event_types text[] not null,
    secret_hash bytea,
    is_enabled boolean not null default true,
    created_by bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (public_id),
    check (length(trim(name)) > 0),
    check (target_url like 'http://%' or target_url like 'https://%'),
    check (cardinality(event_types) > 0)
);

create table if not exists notification_targets (
    id bigserial primary key,
    public_id uuid not null default gen_random_uuid(),
    name text not null,
    target_type text not null,
    plugin_id text,
    config jsonb not null default '{}'::jsonb,
    secret_ref text,
    is_enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (public_id),
    check (length(trim(name)) > 0),
    check (target_type in ('telegram', 'wecom', 'webhook', 'plugin'))
);

create table if not exists playback_sessions (
    id bigserial primary key,
    public_id uuid not null default gen_random_uuid(),
    user_id bigint not null references users(id) on delete cascade,
    device_id bigint references devices(id) on delete set null,
    media_item_id bigint not null references media_items(id) on delete cascade,
    media_file_id bigint references media_files(id) on delete set null,
    play_method text not null,
    position_ticks bigint not null default 0,
    is_paused boolean not null default false,
    started_at timestamptz not null default now(),
    last_progress_at timestamptz not null default now(),
    stopped_at timestamptz,
    client_session_id text,
    remote_addr inet,
    unique (public_id),
    check (play_method in ('direct_play', 'direct_stream', 'transcode', 'strm_redirect')),
    check (position_ticks >= 0),
    check (stopped_at is null or stopped_at >= started_at)
);

create table if not exists user_playstates (
    id bigserial primary key,
    user_id bigint not null references users(id) on delete cascade,
    media_item_id bigint not null references media_items(id) on delete cascade,
    played boolean not null default false,
    play_count integer not null default 0,
    position_ticks bigint not null default 0,
    last_played_at timestamptz,
    updated_at timestamptz not null default now(),
    unique (user_id, media_item_id),
    check (play_count >= 0),
    check (position_ticks >= 0)
);

create table if not exists transcoding_sessions (
    id bigserial primary key,
    public_id uuid not null default gen_random_uuid(),
    playback_session_id bigint references playback_sessions(id) on delete set null,
    user_id bigint not null references users(id) on delete cascade,
    media_item_id bigint not null references media_items(id) on delete cascade,
    media_file_id bigint references media_files(id) on delete set null,
    job_id bigint references jobs(id) on delete set null,
    status text not null default 'queued',
    hardware_acceleration text,
    input_path text,
    output_path text,
    manifest_path text,
    video_codec text,
    audio_codec text,
    container text,
    bitrate integer,
    started_at timestamptz,
    last_segment_at timestamptz,
    finished_at timestamptz,
    error_message text,
    created_at timestamptz not null default now(),
    unique (public_id),
    check (status in ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
    check (bitrate is null or bitrate >= 0),
    check (finished_at is null or started_at is null or finished_at >= started_at)
);
